version: '3.6'
services:
  web:
    image: 'gitlab/gitlab-ce:15.2.2-ce.0'
    restart: always
    hostname: 'gitlab-local'
    environment:
      GITLAB_ROOT_PASSWORD: 'root123!'
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab-local'
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
    shm_size: '256m'