version: '3.7'

services:
  server:
    # https://hub.docker.com/r/gitea/gitea/tags
    #image: gitea/gitea:1.11.0
    image: gitea/gitea:1.12.5
    hostname: local-gitea
    container_name: local-gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - INSTALL_LOCK=true
      - PASSWORD_COMPLEXITY=off
      - SSH_PORT=222
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea:/data
    ports:
      - "3000:3000"
      - "222:22"

networks:
  gitea:
    name: "gitea-network"